"""phase_1_vas_ms_v2_core_models

Revision ID: 4fc741f726dd
Revises: 3b53dc2e5aab
Create Date: 2026-01-09 12:22:10.327718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4fc741f726dd'
down_revision: Union[str, None] = '3b53dc2e5aab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jwt_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_secret_hash', sa.String(length=255), nullable=False),
    sa.Column('scopes', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jwt_tokens_client_id'), 'jwt_tokens', ['client_id'], unique=True)
    op.create_index(op.f('ix_jwt_tokens_is_active'), 'jwt_tokens', ['is_active'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_client_id'), 'refresh_tokens', ['client_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_is_revoked'), 'refresh_tokens', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_table('streams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.Enum('INITIALIZING', 'READY', 'LIVE', 'ERROR', 'STOPPED', 'CLOSED', name='stream_state'), nullable=False),
    sa.Column('codec_config', sa.JSON(), nullable=False),
    sa.Column('access_policy', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streams_camera_id'), 'streams', ['camera_id'], unique=False)
    op.create_index(op.f('ix_streams_name'), 'streams', ['name'], unique=False)
    op.create_index(op.f('ix_streams_state'), 'streams', ['state'], unique=False)
    op.create_table('consumers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stream_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('mediasoup_consumer_id', sa.String(length=255), nullable=False),
    sa.Column('mediasoup_transport_id', sa.String(length=255), nullable=False),
    sa.Column('state', sa.Enum('CONNECTING', 'CONNECTED', 'PAUSED', 'CLOSED', name='consumer_state'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumers_client_id'), 'consumers', ['client_id'], unique=False)
    op.create_index(op.f('ix_consumers_mediasoup_consumer_id'), 'consumers', ['mediasoup_consumer_id'], unique=True)
    op.create_index(op.f('ix_consumers_state'), 'consumers', ['state'], unique=False)
    op.create_index(op.f('ix_consumers_stream_id'), 'consumers', ['stream_id'], unique=False)
    op.create_table('producers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stream_id', sa.UUID(), nullable=False),
    sa.Column('mediasoup_producer_id', sa.String(length=255), nullable=False),
    sa.Column('mediasoup_transport_id', sa.String(length=255), nullable=False),
    sa.Column('mediasoup_router_id', sa.String(length=255), nullable=False),
    sa.Column('ssrc', sa.BigInteger(), nullable=False),
    sa.Column('rtp_parameters', sa.JSON(), nullable=False),
    sa.Column('state', sa.Enum('CREATING', 'ACTIVE', 'PAUSED', 'CLOSED', name='producer_state'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_producers_mediasoup_producer_id'), 'producers', ['mediasoup_producer_id'], unique=True)
    op.create_index(op.f('ix_producers_state'), 'producers', ['state'], unique=False)
    op.create_index(op.f('ix_producers_stream_id'), 'producers', ['stream_id'], unique=False)
    op.create_table('stream_state_transitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stream_id', sa.UUID(), nullable=False),
    sa.Column('from_state', sa.String(length=20), nullable=True),
    sa.Column('to_state', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stream_state_transitions_created_at'), 'stream_state_transitions', ['created_at'], unique=False)
    op.create_index(op.f('ix_stream_state_transitions_stream_id'), 'stream_state_transitions', ['stream_id'], unique=False)
    op.create_index(op.f('ix_stream_state_transitions_to_state'), 'stream_state_transitions', ['to_state'], unique=False)
    op.alter_column('api_keys', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint('api_keys_key_key', 'api_keys', type_='unique')
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_key'), 'api_keys', ['key'], unique=True)
    op.add_column('bookmarks', sa.Column('stream_id', sa.UUID(), nullable=False))
    op.add_column('bookmarks', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('bookmarks', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('bookmarks', sa.Column('event_type', sa.String(length=50), nullable=True))
    op.add_column('bookmarks', sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('bookmarks', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_bookmarks_center_timestamp'), 'bookmarks', ['center_timestamp'], unique=False)
    op.create_index(op.f('ix_bookmarks_created_at'), 'bookmarks', ['created_at'], unique=False)
    op.create_index(op.f('ix_bookmarks_created_by'), 'bookmarks', ['created_by'], unique=False)
    op.create_index(op.f('ix_bookmarks_event_type'), 'bookmarks', ['event_type'], unique=False)
    op.create_index(op.f('ix_bookmarks_stream_id'), 'bookmarks', ['stream_id'], unique=False)
    op.drop_constraint('bookmarks_device_id_fkey', 'bookmarks', type_='foreignkey')
    op.create_foreign_key(None, 'bookmarks', 'streams', ['stream_id'], ['id'], ondelete='CASCADE')
    op.drop_column('bookmarks', 'device_id')
    op.add_column('snapshots', sa.Column('stream_id', sa.UUID(), nullable=False))
    op.add_column('snapshots', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('snapshots', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('snapshots', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('snapshots', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_snapshots_created_at'), 'snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_snapshots_created_by'), 'snapshots', ['created_by'], unique=False)
    op.create_index(op.f('ix_snapshots_stream_id'), 'snapshots', ['stream_id'], unique=False)
    op.create_index(op.f('ix_snapshots_timestamp'), 'snapshots', ['timestamp'], unique=False)
    op.drop_constraint('snapshots_device_id_fkey', 'snapshots', type_='foreignkey')
    op.create_foreign_key(None, 'snapshots', 'streams', ['stream_id'], ['id'], ondelete='CASCADE')
    op.drop_column('snapshots', 'device_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snapshots', sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'snapshots', type_='foreignkey')
    op.create_foreign_key('snapshots_device_id_fkey', 'snapshots', 'devices', ['device_id'], ['id'])
    op.drop_index(op.f('ix_snapshots_timestamp'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_stream_id'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_created_by'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_created_at'), table_name='snapshots')
    op.drop_column('snapshots', 'metadata')
    op.drop_column('snapshots', 'height')
    op.drop_column('snapshots', 'width')
    op.drop_column('snapshots', 'created_by')
    op.drop_column('snapshots', 'stream_id')
    op.add_column('bookmarks', sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bookmarks', type_='foreignkey')
    op.create_foreign_key('bookmarks_device_id_fkey', 'bookmarks', 'devices', ['device_id'], ['id'])
    op.drop_index(op.f('ix_bookmarks_stream_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_event_type'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_created_by'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_created_at'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_center_timestamp'), table_name='bookmarks')
    op.drop_column('bookmarks', 'metadata')
    op.drop_column('bookmarks', 'tags')
    op.drop_column('bookmarks', 'event_type')
    op.drop_column('bookmarks', 'confidence')
    op.drop_column('bookmarks', 'created_by')
    op.drop_column('bookmarks', 'stream_id')
    op.drop_index(op.f('ix_api_keys_key'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.create_unique_constraint('api_keys_key_key', 'api_keys', ['key'])
    op.alter_column('api_keys', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_stream_state_transitions_to_state'), table_name='stream_state_transitions')
    op.drop_index(op.f('ix_stream_state_transitions_stream_id'), table_name='stream_state_transitions')
    op.drop_index(op.f('ix_stream_state_transitions_created_at'), table_name='stream_state_transitions')
    op.drop_table('stream_state_transitions')
    op.drop_index(op.f('ix_producers_stream_id'), table_name='producers')
    op.drop_index(op.f('ix_producers_state'), table_name='producers')
    op.drop_index(op.f('ix_producers_mediasoup_producer_id'), table_name='producers')
    op.drop_table('producers')
    op.drop_index(op.f('ix_consumers_stream_id'), table_name='consumers')
    op.drop_index(op.f('ix_consumers_state'), table_name='consumers')
    op.drop_index(op.f('ix_consumers_mediasoup_consumer_id'), table_name='consumers')
    op.drop_index(op.f('ix_consumers_client_id'), table_name='consumers')
    op.drop_table('consumers')
    op.drop_index(op.f('ix_streams_state'), table_name='streams')
    op.drop_index(op.f('ix_streams_name'), table_name='streams')
    op.drop_index(op.f('ix_streams_camera_id'), table_name='streams')
    op.drop_table('streams')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_is_revoked'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_client_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_jwt_tokens_is_active'), table_name='jwt_tokens')
    op.drop_index(op.f('ix_jwt_tokens_client_id'), table_name='jwt_tokens')
    op.drop_table('jwt_tokens')
    # ### end Alembic commands ###


